site :opscode

cookbook 'postgresql', github: 'phlipper/chef-postgresql'
cookbook 'git'
cookbook 'runit'
cookbook 'python'
cookbook 'pgrest', github: 'clkao-cookbooks/pgrest'
cookbook 'apt', github: 'opscode-cookbooks/apt'
cookbook 'nodejs', github: 'phlipper/chef-nodejs'
cookbook 'kuansim', path: '.'
