site :opscode

cookbook 'postgresql'
cookbook 'git'
cookbook 'runit'
cookbook 'python'
cookbook 'pgrest'
cookbook 'apt', github: 'opscode-cookbooks/apt'
cookbook 'nodejs', github: 'phlipper/chef-nodejs'
cookbook 'kuansim', path: '.'
